/**
 * Le rempotage des vivaces en pot : tous les combien d'années, à quels mois, si l'on change la terre du dessus
 * (5 cm de terreau neuf) les autres années, et le signe qu'elle manque de place. Vérifié le 6 octobre 2026 par
 * recherche web (2 sources au moins, culture en pot) ; quand les sources divergeaient, la fourchette couvre les
 * deux. Détail des choix : docs/sources-calendrier.md.
 */

export type Repotting = {
  /** Tous les combien d'années la passer dans un pot plus grand. */
  everyYears: [number, number];
  /** Mois conseillés (1 à 12). */
  months: number[];
  /** Les autres années : changer les 5 cm de terre du dessus. */
  topdress: boolean;
  /** Le signe qu'elle manque de place, au tutoiement. */
  sign: string | null;
  sources: string[];
};

export const REPOTTING: Record<string, Repotting> = {
  "mint": { everyYears: [1, 1], months: [3, 4, 9, 10], topdress: false, sign: "Si ta menthe pousse plus faible et que ses feuilles sentent moins, c'est que la terre est épuisée : rempote-la.", sources: ["https://www.jardiner-malin.fr/fiche/menthe-en-pot.html", "https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/reussir-menthe-pot/", "https://www.gerbeaud.com/jardin/fiches/menthe.php"] },
  "chives": { everyYears: [1, 1], months: [3, 4, 9, 10], topdress: true, sign: "Si les nouvelles tiges sont plus fines et plus claires, ta ciboulette a besoin de terre neuve.", sources: ["https://www.jardiner-malin.fr/fiche/ciboulette-en-pot.html", "https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/ciboulette-en-pot/", "https://www.gerbeaud.com/jardin/fiches/fp_ciboulette_division.php3"] },
  "thyme": { everyYears: [2, 4], months: [3, 4], topdress: true, sign: "Si l'eau traverse le pot sans mouiller la terre et que des racines sortent par le trou, rempote ton thym.", sources: ["https://www.jardiner-malin.fr/fiche/thym-en-pot.html", "https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/comment-cultiver-thym-pot/", "https://www.123lesplantes.fr/entretien/plante-de-jardin-thym"] },
  "rosemary": { everyYears: [2, 3], months: [3, 4], topdress: true, sign: "Quand les racines occupent tout le pot, offre à ton romarin un pot plus grand.", sources: ["https://www.jardiner-malin.fr/fiche/romarin-en-pot.html", "https://www.proscot.fr/cultiver-romarin-en-pot", "https://octo-jardin.fr/romarin/"] },
  "sage": { everyYears: [2, 3], months: [3, 4, 5], topdress: true, sign: "Si des racines sortent par les trous du pot, ta sauge veut un pot plus grand.", sources: ["https://www.jardiner-malin.fr/fiche/sauge-en-pot.html", "https://www.catharsius.fr/plante-sauge-officinale/soin/guide-de-rempotage/", "https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/comment-cultiver-une-sauge-arbustive-en-pot/"] },
  "oregano": { everyYears: [2, 3], months: [3, 4], topdress: true, sign: null, sources: ["https://www.jardiner-malin.fr/fiche/origan-en-pot.html", "https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/cultiver-origan-en-pot/"] },
  "lemon-balm": { everyYears: [2, 3], months: [3, 4, 10], topdress: true, sign: "Si les racines sont à l'étroit, rempote ta mélisse et profites-en pour diviser la touffe.", sources: ["https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/cultiver-la-melisse-en-pot/", "https://www.gerbeaud.com/jardin/fiches/plantes-aromatiques-travaux-entretien-printemps,2918.html", "https://jardinage.pagesjaunes.fr/plante/voir/464/melisse"] },
  "lemon-verbena": { everyYears: [2, 2], months: [3, 4, 5], topdress: true, sign: "Si ta verveine semble à l'étroit dans son pot, rempote-la au printemps.", sources: ["https://www.gerbeaud.com/jardin/fiches/verveine-citronnelle.php", "https://www.gammvert.fr/conseils-idees/comment-planter-la-verveine-citronnelle", "https://www.lapousseverte.fr/2021/06/04/verveine-citronnelle-conseils-jardinage-pour-votre-plante/"] },
  "tarragon": { everyYears: [2, 3], months: [3, 4], topdress: true, sign: null, sources: ["https://binette-et-cornichon.com/p/estragon/", "https://jardinerbio.com/estragon-en-pot-culture-abondante-balcon/", "https://www.jardiner-malin.fr/fiche/estragon.html"] },
  "savory": { everyYears: [2, 3], months: [3, 4, 5], topdress: true, sign: "Si ta sarriette est à l'étroit dans son pot, rempote-la au printemps.", sources: ["https://www.gerbeaud.com/jardin/fiches/sarriette.php", "https://www.promessedefleurs.com/conseil-plantes-jardin/fichefamille/sarriette-semis-culture-recolte/", "https://binette-et-cornichon.com/p/sarriette/"] },
  "lemongrass": { everyYears: [2, 2], months: [4, 5], topdress: true, sign: null, sources: ["https://www.jardiner-malin.fr/fiche/citronnelle.html", "https://www.gerbeaud.com/jardin/fiches/citronnelle,1469.html", "https://www.catharsius.fr/plante-citronnelle/soin/methodes-de-propagation/"] },
  "stevia": { everyYears: [1, 1], months: [3, 4], topdress: false, sign: "Si tu dois arroser ta stévia plus d'une fois par semaine, ses racines manquent de place.", sources: ["https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/cultiver-la-stevia/", "https://jardinierparesseux.com/2020/01/26/le-stevia-les-jardiniers-aiment-le-vrai/", "https://www.autourdupotager.com/la-culture-de-la-stevia/"] },
  "hyssop": { everyYears: [2, 3], months: [3, 4, 9, 10], topdress: true, sign: null, sources: ["https://jardinerbio.com/hysope-culture-entretien-usages/", "https://www.gerbeaud.com/jardin/fiches/hysope.php", "https://www.promessedefleurs.com/conseil-plantes-jardin/fichefamille/hysope-hyssopus-officinale-semis-plantation-culture-bienfaits/"] },
  "wild-garlic": { everyYears: [3, 5], months: [6, 9, 10], topdress: true, sign: null, sources: ["https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/cultiver-ail-des-ours-en-pot/", "https://www.jardiner-malin.fr/fiche/ail-des-ours-en-pot.html", "https://jardinerbio.com/l-ail-des-ours-guide-complet-culture-usages/"] },
  "agastache": { everyYears: [2, 3], months: [3, 4, 5], topdress: true, sign: null, sources: ["https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/cultiver-agastache-en-pot/", "https://www.leaderplant.com/blog/l-agastache-la-vivace-aromatique-aux-fleurs-melliferes", "https://conseils-jardin.willemsefrance.fr/agastache-conseil/"] },
  "lovage": { everyYears: [2, 3], months: [3, 4, 10], topdress: true, sign: "Si les racines sont à l'étroit, passe ta livèche dans un pot plus grand au printemps.", sources: ["https://www.gerbeaud.com/jardin/fiches/plantes-aromatiques-travaux-entretien-printemps,2918.html", "https://www.jardiner-malin.fr/fiche/liveche.html", "https://www.autourdupotager.com/liveche/"] },
  "oyster-plant": { everyYears: [2, 3], months: [3, 4], topdress: false, sign: null, sources: ["https://www.gerbeaud.com/jardin/fiches/mertensia-maritima-plante-huitre,1392.html", "https://www.promessedefleurs.com/conseil-plantes-jardin/fichefamille/mertensia-maritima-semis-culture-recolte/", "https://www.terrevivante.org/contenu/mertensia-maritima-plante-huitre/"] },
  "pineapple-sage": { everyYears: [1, 3], months: [3, 4, 5], topdress: true, sign: "Si ta sauge ananas pousse moins et fleurit peu, c'est qu'elle a dépassé son pot.", sources: ["https://www.promessedefleurs.com/vivaces/vivaces-par-variete/sauges/salvia-elegans-sauge-ananas.html", "https://www.weplant.fr/care/salvia", "https://www.jardiner-malin.fr/fiche/sauge-en-pot.html"] },
  "strawberry": { everyYears: [3, 4], months: [3, 4, 9, 10], topdress: true, sign: null, sources: ["https://www.catharsius.fr/comment-faire-pousser-fraises-pot/", "https://www.gammvert.fr/conseils-idees/planter-des-fraisiers-en-pot", "https://www.jardiner-malin.fr/fiche/fraise-fraisier-en-pot.html"] },
  "sorrel": { everyYears: [1, 3], months: [3, 4, 9, 10], topdress: true, sign: null, sources: ["https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/culture-oseille-en-pot/", "https://www.promessedefleurs.com/conseil-plantes-jardin/tutoriel/comment-diviser-l-oseille-au-jardin-potager/", "https://binette-et-cornichon.com/p/oseille/"] },
  "perpetual-leek": { everyYears: [2, 3], months: [3, 4, 9, 10], topdress: false, sign: "Si la touffe devient trop serrée et donne des poireaux plus fins, divise-la et rempote.", sources: ["https://jardinierdudimanche.fr/poireau-perpetuel-le-guide-complet-pour-une-culture-reussie/", "https://lepotagerdolivier.com/poireau-perpetuel-culture-entretien-et-recolte", "https://www.jardiner-malin.fr/fiche/poireau-perpetuel.html"] },
  "crosne": { everyYears: [1, 1], months: [3, 4], topdress: false, sign: null, sources: ["https://aromesetfruits.fr/products/crosnes-du-japon", "https://www.gerbeaud.com/jardin/fiches/crosne-japon,1157.html", "https://www.promessedefleurs.com/conseil-plantes-jardin/fichefamille/le-crosne-cultiver/"] },
  "lavender": { everyYears: [2, 3], months: [3, 4, 5], topdress: true, sign: "Si des racines sortent par les trous du pot ou si la terre sèche en un jour, passe à un pot un peu plus grand.", sources: ["https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/lavande-en-pot/", "https://www.jardiland.com/conseils-idees/comment-reussir-culture-lavande-en-pot", "https://www.truffaut.com/lavande-plantation-entretien.html"] },
  "hardy-geranium": { everyYears: [3, 5], months: [3, 4], topdress: false, sign: "Si ta touffe devient très dense et fleurit moins, divise-la au printemps.", sources: ["https://www.aujardin.info/plantes/geranium-vivace.php", "https://www.gammvert.fr/conseils-idees/geranium-vivace", "https://www.promessedefleurs.com/conseil-plantes-jardin/fichefamille/geraniums-vivaces-planter-cultiver-et-entretenir/"] },
  "tall-verbena": { everyYears: [2, 2], months: [3, 4], topdress: false, sign: null, sources: ["https://www.truffaut.com/verveine-buenos-aires.html", "https://lagreentouch.fr/blogs/conseils-entretien-plantes/fiche-entretien-verveine-de-buenos-aires-verbena-bonariensis", "https://www.gerbeaud.com/jardin/fiches/verveine-de-buenos-aires,1533.html"] },
  "pinks": { everyYears: [1, 3], months: [3, 4, 9], topdress: false, sign: "Si ta touffe se dégarnit au centre, divise-la pour la rajeunir.", sources: ["https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/cultiver-oeillet-en-pot/", "https://www.jardiner-malin.fr/fiche/oeillet-mignardise.html"] },
  "dahlia": { everyYears: [1, 1], months: [3, 4, 5], topdress: false, sign: null, sources: ["https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/dahlia-en-pot/", "https://www.planfor.fr/jardin-conseils,les-dahlias-en-pot.html", "https://www.compo.be/fr/conseil/entretien-des-plantes/plantes-balcon-bac/hivernage-dahlias"] },
  "fuchsia": { everyYears: [1, 3], months: [3, 4], topdress: true, sign: "Si des racines sortent par les trous du pot ou si la terre sèche en un jour, passe à un pot un peu plus grand.", sources: ["https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/cultiver-fuchsia-en-pot/", "https://www.jardiner-malin.fr/fiche/fuchsia-planter-floraison.html", "https://www.gerbeaud.com/jardin/fiches/fuchsia-sortie-hivernage,1693.html"] },
  "dwarf-raspberry": { everyYears: [2, 3], months: [3, 4], topdress: true, sign: "Si des racines sortent par les trous du pot ou si la terre sèche en un jour, passe à un pot un peu plus grand.", sources: ["https://www.jardiner-malin.fr/fiche/framboisier-en-pot.html", "https://www.expertjardins.com/framboisier-en-pot-guide-complet-pour-debutants/", "https://plantes-et-jardin-de-ville.com/culture-du-framboisier-en-pot/"] },
  "blueberry": { everyYears: [2, 3], months: [3, 4], topdress: true, sign: "Si des racines sortent par les trous du pot ou si la terre sèche en un jour, passe à un pot un peu plus grand.", sources: ["https://www.promessedefleurs.com/conseil-plantes-jardin/fichefamille/myrtillier-planter-tailler-entretenir/", "https://www.lesjardinsdelaterre.com/blog/conseils-plantes/vaccinium-corymbosum-en-pot-comment-cultiver-des-myrtilles-sur-votre-balcon-", "https://www.pretajardiner.com/855-myrtillier"] },
  "redcurrant": { everyYears: [2, 4], months: [2, 3, 10, 11], topdress: true, sign: "Si des racines tournent en rond contre la paroi ou sortent du pot, passe à un pot plus grand.", sources: ["https://lagreentouch.fr/blogs/conseils-entretien-plantes/fiche-entretien-groseillier-a-grappes-ribes-rubrum", "https://www.jardiner-malin.fr/fiche/groseillier-en-pot.html", "https://www.lubera.fr/journal/groseilliers-en-bac-p1310"] },
  "lemon-tree": { everyYears: [2, 3], months: [3, 4, 5], topdress: true, sign: "Quand des racines sortent par les trous du pot, passe à un pot à peine plus grand.", sources: ["https://www.jardiner-malin.fr/fiche/citronnier-en-pot.html", "https://www.ecoledagriculture.fr/citronniers-en-pot-le-surfacage-express-qui-booste-leur-production/", "https://fousdagrumes.com/citronnier-en-pot"] },
  "dwarf-fig": { everyYears: [2, 3], months: [3, 4], topdress: true, sign: "Si des racines sortent par les trous du pot ou si la terre sèche en un jour, passe à un pot un peu plus grand.", sources: ["https://www.promessedefleurs.com/conseil-plantes-jardin/ficheconseil/culture-figuier-en-pot/", "https://www.plantezcheznous.com/blog/rempoter-un-figuier-achete-en-container/", "https://plantandstories.com/en/blogs/plantes-exterieur-jardin/figuier-entretien-plantation-taille-rusticite-guide"] },
  "woodland-strawberry": { everyYears: [3, 4], months: [3, 4, 9], topdress: true, sign: "Si ton fraisier donne de moins en moins de fraises, remplace-le par un jeune stolon.", sources: ["https://www.gammvert.fr/conseils-idees/planter-des-fraisiers-en-pot", "https://lagreentouch.fr/blogs/conseils-entretien-plantes/fiche-entretien-fraisier-des-bois-fragaria-vesca-guide-pratique", "https://www.jardiner-malin.fr/fiche/fraise-fraisier-en-pot.html"] },
  "kiwiberry": { everyYears: [2, 5], months: [3, 4], topdress: true, sign: "Si des racines sortent par les trous du pot ou si la terre sèche en un jour, passe à un pot un peu plus grand.", sources: ["https://lagreentouch.fr/blogs/conseils-entretien-plantes/fiche-entretien-kiwi-actinidia-arguta-guide-pratique", "https://plantes-et-jardin-de-ville.com/culture-kiwi-pot/"] },
  "blackcurrant": { everyYears: [2, 3], months: [3, 4], topdress: true, sign: "Si des racines sortent par les trous du pot ou si la terre sèche en un jour, passe à un pot un peu plus grand.", sources: ["https://www.jardiner-malin.fr/fiche/cassissier-en-pot.html", "https://lagreentouch.fr/blogs/conseils-entretien-plantes/fiche-entretien-cassis-ribes-nigrum", "https://www.pretajardiner.com/852-cassissier"] },
  "thornless-blackberry": { everyYears: [2, 4], months: [3, 4], topdress: false, sign: "Si des racines sortent par les trous du pot ou si la terre sèche en un jour, passe à un pot un peu plus grand.", sources: ["https://www.lubera.fr/journal/cultiver-un-murier-en-pot-p5606", "https://lagreentouch.fr/blogs/conseils-entretien-plantes/fiche-entretien-murier-sans-epines-rubus-fruticosus-guide-pratique"] },
};
