/**
 * La banque d'astuces de saison (carte « Astuce » d'Aujourd'hui). Chaque astuce est vérifiée sur deux sources au moins,
 * relue face au calendrier des plantes : sources et changements dans docs/astuces.md. Fichier de données : pour ajouter
 * une astuce, la vérifier, l'ajouter ici et dans docs/astuces.md.
 */
import type { Tip } from "./tips";

export const TIP_BANK: Tip[] = [
  { id: "jan-graines", text: "Fais l’inventaire de tes graines : un sachet ouvert se garde souvent 2 à 3 ans au sec. Au-delà, elles germent moins bien.", months: [1] },
  { id: "jan-thym-eau", text: "Ton thym craint plus l’humidité que le froid. Arrose seulement si la terre est sèche depuis longtemps et qu’il ne gèle pas.", months: [1], plants: ["thyme", "rosemary", "lavender", "sage"] },
  { id: "jan-cales", text: "Les pots gèlent plus vite que la pleine terre. Pose-les sur des cales : l’eau s’écoule et le froid du sol ne remonte pas.", months: [1, 2], condition: "frost" },
  { id: "jan-micropousses", text: "Sème des micro-pousses dans une barquette, près de ta fenêtre : en hiver, elles se récoltent en dix à quinze jours.", months: [1, 2], about: ["microgreens"] },
  { id: "jan-pots-propres", text: "Lave tes pots vides à l’eau savonneuse, rince et laisse sécher : tu ne gardes pas les maladies de l’an passé pour le printemps.", months: [1, 2] },
  { id: "jan-oiseaux", text: "Pose des graines de tournesol ou une boule de graisse sans filet pour les mésanges, jusqu’à fin mars. Au printemps, elles mangeront chenilles et insectes.", months: [1, 2] },
  { id: "jan-kale", text: "Ton chou kale devient plus tendre et plus doux après les gelées. Cueille ses feuilles du bas, au fil de l’hiver.", months: [1, 2], plants: ["kale"] },
  { id: "jan-citronnier", text: "Ton citronnier passe l’hiver au frais et à la lumière, entre 5 et 12 °C. Arrose seulement quand la terre est sèche en surface.", months: [1, 2], plants: ["lemon-tree"] },
  { id: "fev-godets", text: "Prépare des godets pour tes semis au chaud : des pots de yaourt percés ou des boîtes d’œufs font très bien l’affaire.", months: [2, 3] },
  { id: "fev-nettoyage", text: "Attends la fin des grands froids pour couper les tiges sèches de tes vivaces : des coccinelles y passent l’hiver. Coupe juste avant les nouvelles pousses.", months: [2, 3], climates: { shift: true } },
  { id: "fev-fraisiers", text: "Coupe les feuilles sèches et abîmées de tes fraisiers, sans toucher au cœur : ils repartiront plus vite au printemps.", months: [2, 3], plants: ["strawberry", "woodland-strawberry"], climates: { shift: true } },
  { id: "fev-vent", text: "Le vent d’hiver dessèche les plantes en pot. Rapproche les plus fragiles d’un mur abrité et regroupe-les : elles se protègent entre elles.", months: [1, 2], condition: "wind" },
  { id: "fev-piments", text: "Sème piments, poivrons et aubergines au chaud dès fin février : ils germent lentement et demandent 20 à 25 °C, près d’une fenêtre lumineuse.", months: [2, 3], about: ["chili", "sweet-pepper", "eggplant"], climates: { shift: true } },
  { id: "fev-pois", text: "Sème tes petits pois directement dans leur pot dès que la terre n’est plus gelée : ils aiment la fraîcheur et n’aiment pas être déplacés.", months: [2, 3], about: ["pea"], climates: { shift: true } },
  { id: "fev-ail", text: "Il est encore temps de planter de l’ail : enfonce chaque gousse pointe en haut, à 5 cm de profondeur, un jour sans gel.", months: [2, 3], about: ["garlic"], climates: { shift: true } },
  { id: "fev-nichoir", text: "Installe un nichoir en bois brut, à l’abri du vent et du plein soleil : les mésanges choisissent leur logement dès la fin de l’hiver.", months: [1, 2] },
  { id: "mar-patience", text: "Ne sors pas tes jeunes tomates trop tôt : au froid, elles arrêtent de pousser. Attends que les nuits restent au-dessus de 10 °C.", months: [3, 4], plants: ["cherry-tomato", "dwarf-tomato"], climates: { shift: true } },
  { id: "mar-terre-dessus", text: "Remplace les 5 premiers centimètres de terre de tes pots de vivaces par du terreau neuf : ça les nourrit pour l’année.", months: [3, 4], climates: { shift: true } },
  { id: "mar-eau-pluie", text: "Récupère l’eau de pluie dans un seau ou un arrosoir : tes plantes la préfèrent souvent à l’eau calcaire du robinet.", months: [3, 4] },
  { id: "mar-profondeur", text: "Sème une graine à deux ou trois fois sa taille de profondeur. Les toutes petites se posent sur la terre, à peine couvertes.", months: [3, 4] },
  { id: "mar-menthe", text: "La menthe envahit tout : garde-la seule dans son pot, jamais mélangée à d’autres plantes.", months: [3, 4], plants: ["mint"] },
  { id: "mar-germer", text: "Un mois avant de planter tes pommes de terre, pose-les dans une boîte d’œufs, à la lumière sans soleil direct : elles feront de petits germes solides.", months: [2, 3], plants: ["potato"], climates: { shift: true } },
  { id: "mar-radis", text: "Sème des radis dès que la terre n’est plus gelée : en un mois environ, tu croques ta première récolte.", months: [3, 4], about: ["radish"], climates: { shift: true } },
  { id: "mar-ciboulette", text: "Ta ciboulette pousse moins ? Divise la touffe en trois ou quatre morceaux avec leurs racines, puis replante-les : elle repartira de plus belle.", months: [3, 4], plants: ["chives"], climates: { shift: true } },
  { id: "avr-endurcir", text: "Habitue tes semis au dehors peu à peu : quelques heures à l’ombre le premier jour, un peu plus chaque jour, et rentre-les la nuit pendant une semaine.", months: [4, 5], climates: { shift: true } },
  { id: "avr-nuits-claires", text: "Gare aux nuits claires d’avril : même après une belle journée, le gel peut revenir jusqu’aux Saints de glace, mi-mai.", months: [4], climates: { only: ["oceanic", "temperate", "continental"] } },
  { id: "avr-gel-mediterranee", text: "Chez toi, les gelées sont en général finies : installe tes tomates cerises et ton basilic dehors quand les nuits restent au-dessus de 10 °C.", months: [4], plants: ["cherry-tomato", "dwarf-tomato", "basil"], climates: { only: ["mediterranean"] } },
  { id: "avr-abeilles", text: "Installe des fleurs mellifères, celles qui nourrissent les abeilles, comme le romarin ou la ciboulette : elles sortent aux premiers beaux jours et cherchent déjà à manger.", months: [4], about: ["rosemary", "chives"] },
  { id: "avr-basilic", text: "Le basilic adore la chaleur : garde-le à l’intérieur, près d’une fenêtre lumineuse, tant que les nuits descendent sous 10 °C.", months: [4], plants: ["basil"], climates: { shift: true } },
  { id: "avr-soucoupe", text: "Une soucoupe pleine d’eau asphyxie les racines. Vide-la une demi-heure après l’arrosage.", months: [4, 5] },
  { id: "avr-radis", text: "Sème des radis dans un pot d’au moins 20 cm : ils se récoltent en trois à cinq semaines. Cueille-les vite, ils deviennent creux en grossissant.", months: [4], about: ["radish"] },
  { id: "avr-aromatiques", text: "C’est le moment de planter thym, romarin et sauge : un pot percé, du terreau mêlé d’un peu de sable, et tout le soleil possible.", months: [4], about: ["thyme", "rosemary", "sage"] },
  { id: "avr-voile-gel", text: "Gel annoncé cette nuit ? Couvre tes jeunes plants d’un voile de jardin sans l’appuyer sur les feuilles, et retire-le le matin quand il fait plus doux.", months: [4, 5], condition: "frost" },
  { id: "mai-saints-glace", text: "Les Saints de glace passés (11 au 13 mai), installe dehors tes tomates cerises, tes poivrons et ton basilic : le risque de gel devient faible.", months: [5], plants: ["cherry-tomato", "dwarf-tomato", "sweet-pepper", "basil"], climates: { only: ["oceanic", "temperate", "continental"] } },
  { id: "mai-montagne", text: "En montagne, attends début juin pour sortir tes tomates cerises et ton basilic : les gelées y reviennent souvent après les Saints de glace.", months: [5], plants: ["cherry-tomato", "dwarf-tomato", "basil"], climates: { only: ["mountain"] } },
  { id: "mai-paillage", text: "Arrose bien, puis couvre la terre de tes pots de 2 à 3 cm de paillettes de chanvre ou de lin : elle garde son humidité bien plus longtemps.", months: [5, 6] },
  { id: "mai-tuteur", text: "Plante le tuteur de tes tomates cerises avant de les mettre en terre : l’enfoncer plus tard abîmerait leurs racines.", months: [5, 6], plants: ["cherry-tomato"], climates: { shift: true } },
  { id: "mai-pucerons", text: "Les pucerons arrivent avec la chaleur. Un jet d’eau, ou un peu de savon noir dilué le soir, suffit souvent à les déloger.", months: [5, 6] },
  { id: "mai-haricots", text: "Sème tes haricots quand la terre est bien réchauffée, vers 12 °C : dans une terre froide et mouillée, les graines pourrissent.", months: [5], plants: ["dwarf-bean", "pole-bean"], climates: { shift: true } },
  { id: "mai-capucines", text: "Sème quelques capucines : les pucerons s’y regroupent souvent plutôt que sur tes légumes. Coupe simplement les tiges envahies.", months: [5], about: ["nasturtium"] },
  { id: "mai-abreuvoir", text: "Pose une soucoupe d’eau garnie de petits cailloux : abeilles et papillons y boivent sans se noyer. Change l’eau souvent.", months: [5, 6, 7] },
  { id: "mai-salades", text: "Sème un peu de salade à couper toutes les trois semaines : tu récoltes sans arrêt, sans tout avoir en même temps.", months: [4, 5], about: ["cut-lettuce"] },
  { id: "juin-gourmands", text: "Retire les gourmands de tes tomates cerises, ces pousses entre la tige et une feuille : pince-les jeunes, la plante produit mieux.", months: [6, 7], plants: ["cherry-tomato"] },
  { id: "juin-arrosage-heure", text: "Arrose tôt le matin, ou le soir au pied : en pleine journée, une bonne partie de l’eau s’évapore avant d’atteindre les racines.", months: [6, 7, 8] },
  { id: "juin-aromatiques", text: "Cueille tes aromatiques le matin, une fois la rosée séchée : c’est là qu’elles ont le plus de parfum.", months: [6, 7] },
  { id: "juin-salades", text: "La chaleur fait monter tes salades en graines : elles fleurissent et deviennent amères. Place-les à la mi-ombre l’après-midi et arrose-les régulièrement.", months: [6, 7], plants: ["cut-lettuce", "head-lettuce"] },
  { id: "juin-basilic-pincer", text: "Quand ton basilic atteint 10 cm, pince le bout des tiges juste au-dessus d’une paire de feuilles : il fait de nouvelles tiges et devient touffu.", months: [6, 7], plants: ["basil"], climates: { shift: true } },
  { id: "juin-fraisiers-stolons", text: "Coupe les stolons de tes fraisiers, ces longues tiges qui rampent : la plante garde sa force pour ses fraises. Garde-en un ou deux pour de nouveaux plants.", months: [6, 7], plants: ["strawberry"] },
  { id: "juin-ail", text: "Récolte ton ail quand la moitié de ses feuilles a jauni, par temps sec. Laisse-le sécher une semaine dans un endroit aéré, à l’abri.", months: [6, 7], plants: ["garlic"] },
  { id: "juin-coccinelles", text: "Laisse vivre les larves de coccinelles, ces petites bêtes noires allongées tachées d’orange : chacune mange des dizaines de pucerons par jour.", months: [5, 6, 7] },
  { id: "juil-pot-sombre", text: "Un pot sombre en plein soleil chauffe les racines. Abrite-le, ou entoure-le d’un tissu clair pendant la canicule.", months: [7, 8], condition: "heat" },
  { id: "juil-vacances", text: "Tu pars ? Regroupe tes pots à l’ombre : ensemble, ils perdent moins d’eau. Le mode vacances prépare tout avec toi.", months: [7, 8] },
  { id: "juil-au-pied", text: "Arrose au pied, pas sur les feuilles : des feuilles souvent mouillées attrapent plus facilement des maladies comme le mildiou.", months: [7, 8] },
  { id: "juil-basilic-fleurs", text: "Coupe les fleurs de ton basilic dès qu’elles apparaissent : ses feuilles restent tendres et parfumées.", months: [7, 8], plants: ["basil"] },
  { id: "juil-bouteille", text: "Pour quelques jours d’absence, perce le bouchon d’une bouteille d’eau et plante-la tête en bas dans le pot. Essaie-la avant de partir.", months: [7, 8] },
  { id: "juil-eau-insectes", text: "Pose une soucoupe d’eau peu profonde avec quelques cailloux : abeilles et oiseaux y boivent sans se noyer. Change l’eau chaque jour.", months: [7, 8] },
  { id: "juil-lavande", text: "Coupe tes épis de lavande le matin, quand la moitié des fleurs sont ouvertes. Suspendus tête en bas au sec, ils parfumeront tes placards.", months: [7], plants: ["lavender"] },
  { id: "juil-courgette", text: "Cueille tes courgettes à 15 ou 20 cm, tous les deux ou trois jours : elles sont plus tendres et la plante en donne davantage.", months: [7, 8, 9], plants: ["zucchini"] },
  { id: "aout-cueillir", text: "Cueille souvent : plus tu récoltes tes tomates cerises et tes haricots, plus la plante en produit.", months: [8], plants: ["cherry-tomato", "dwarf-bean", "pole-bean"] },
  { id: "aout-semis-automne", text: "Sème mâche et roquette dès la fin août : elles aiment les jours qui raccourcissent et se récoltent cet automne.", months: [8, 9], about: ["lambs-lettuce", "arugula"] },
  { id: "aout-graines", text: "Laisse sécher sur la plante quelques gousses de tes plus beaux haricots, puis garde leurs graines. Évite les variétés hybrides (F1) : elles ne redonnent pas la même plante.", months: [8, 9], plants: ["dwarf-bean", "pole-bean"] },
  { id: "aout-canicule-eau", text: "Pendant une canicule, arrose copieusement le soir ou tôt le matin, au pied : c’est mieux que plusieurs petits arrosages dans la journée.", months: [6, 7, 8], condition: "heat" },
  { id: "aout-stolons", text: "Pique les petites plantes au bout des longs filets de tes fraisiers dans un godet de terreau. Coupe le filet quand elles ont des racines : fraisiers gratuits !", months: [8, 9], plants: ["strawberry"] },
  { id: "aout-tomates-tete", text: "Fin août, coupe le haut de tes pieds de tomates cerises au-dessus d’un bouquet de fleurs : les fruits déjà formés mûriront avant le froid.", months: [8], plants: ["cherry-tomato"] },
  { id: "aout-lavande-taille", text: "Après la floraison, taille ta lavande d’un tiers, sans couper dans le bois nu, sans feuilles : il ne repartirait pas.", months: [8, 9], plants: ["lavender"] },
  { id: "aout-pensees", text: "Sème des pensées à la mi-ombre, sans enterrer leurs graines toutes fines : elles fleuriront ton balcon de l’automne au printemps.", months: [7, 8], about: ["viola"] },
  { id: "sep-fraisiers", text: "Plante tes fraisiers maintenant : la terre encore chaude les aide à s’enraciner avant l’hiver, et ils donnent des fraises dès le printemps.", months: [9], about: ["strawberry"] },
  { id: "sep-tomates-vertes", text: "Avant les gelées, cueille tes dernières tomates, même vertes, si elles sont saines. Elles finiront de mûrir à l’intérieur, près d’une pomme.", months: [9, 10], plants: ["cherry-tomato"] },
  { id: "sep-boutures", text: "Fais des boutures : coupe une tige sans fleur de 10 cm, retire les feuilles du bas et plante-la dans un pot de terreau léger, gardé humide.", months: [8, 9], plants: ["rosemary", "sage", "lavender"] },
  { id: "sep-feuilles", text: "Ramasse les feuilles mortes saines : étalées sur tes pots, elles font un paillage gratuit qui protège les racines cet hiver.", months: [10, 11] },
  { id: "sep-epinards", text: "Sème des épinards à partir de mi-septembre : ils aiment la fraîcheur et se cueillent feuille à feuille cet automne.", months: [9], about: ["spinach"] },
  { id: "sep-graines-fleurs", text: "Par temps sec, récolte les graines de tes soucis, capucines et cosmos fanés. Fais-les sécher, puis range-les dans une enveloppe en papier avec leur nom.", months: [9, 10], plants: ["calendula", "nasturtium", "cosmos"] },
  { id: "sep-diviser", text: "Ta ciboulette ou ta menthe est trop serrée ? Coupe la touffe en deux avec ses racines et replante chaque morceau : deux pots pour le prix d’un.", months: [9, 10], plants: ["chives", "mint"] },
  { id: "sep-pensees", text: "Un pot s’est libéré ? Installe des pensées : elles fleurissent par temps doux tout l’hiver et repartent de plus belle au printemps.", months: [9, 10], about: ["viola"] },
  { id: "sep-arrosage", text: "Septembre peut encore être chaud. Avant d’arroser, enfonce ton doigt dans la terre : sèche sur 3 cm, arrose ; encore humide, attends.", months: [9] },
  { id: "oct-ail", text: "Plante ton ail en octobre ou novembre, pointe vers le haut : il a besoin du froid de l’hiver pour bien démarrer au printemps.", months: [10, 11], plants: ["garlic"] },
  { id: "oct-moins-eau", text: "Réduis l’arrosage : avec la fraîcheur, la terre sèche bien moins vite qu’en été. Touche-la avant d’arroser.", months: [10] },
  { id: "oct-racines", text: "Quand une annuelle a fini, coupe-la au ras de la terre et laisse les racines : en se décomposant, elles nourrissent le pot. Retire-la entière si elle était malade.", months: [10, 11] },
  { id: "oct-frileuses", text: "Repère tes plantes frileuses, comme le basilic, le piment ou le citronnier : au premier gel annoncé, ce sont elles qu’il faudra récolter ou abriter en premier.", months: [10], plants: ["basil", "chili", "lemon-tree"] },
  { id: "oct-mache", text: "Sème encore de la mâche début octobre, directement dans le pot : elle se récoltera de l’hiver au printemps.", months: [10], about: ["lambs-lettuce"] },
  { id: "oct-violas", text: "Plante des violas ou des pensées : par temps doux, elles fleurissent une bonne partie de l’hiver et égaient ton balcon jusqu’au printemps.", months: [10, 11], about: ["viola"] },
  { id: "oct-citronnier", text: "Rentre ton citronnier avant le gel, dans une pièce claire et fraîche, sans chauffage : vers 5 à 10 °C, il se repose sans perdre ses feuilles.", months: [10, 11, 12], plants: ["lemon-tree"], condition: "frost" },
  { id: "oct-tiges-seches", text: "Laisse quelques tiges sèches et fleurs fanées jusqu’au printemps : des abeilles sauvages et des coccinelles s’y abritent l’hiver, et les oiseaux picorent les graines.", months: [10, 11] },
  { id: "nov-sainte-catherine", text: "« À la Sainte-Catherine, tout bois prend racine » : c’est le moment de planter un framboisier, un groseillier ou un cassissier dans un grand pot.", months: [11], about: ["dwarf-raspberry", "redcurrant", "blackcurrant"] },
  { id: "nov-voile", text: "En pot, ce sont surtout les racines qui craignent le gel. Entoure les pots fragiles de papier bulle ou de toile de jute avant les grands froids.", months: [11, 12], condition: "frost" },
  { id: "nov-terre-cuite", text: "Un pot en terre cuite gorgé d’eau peut éclater au gel. Vide les soucoupes et surélève le pot sur des cales.", months: [11, 12], condition: "frost" },
  { id: "nov-romarin", text: "Ton romarin et ton thym se récoltent aussi l’hiver : prends quelques brins, sans couper plus d’un tiers de la plante.", months: [11, 12, 1, 2], plants: ["rosemary", "thyme"] },
  { id: "nov-mangeoire", text: "Installe une petite mangeoire à l’abri des chats : la LPO conseille de nourrir les oiseaux de mi-novembre à fin mars, pas au-delà.", months: [11, 12, 1, 2, 3] },
  { id: "nov-feuilles", text: "Étale 5 cm de feuilles mortes sur la terre de tes pots, sans tasser : ce paillage, une couverture naturelle, garde les racines au chaud.", months: [11] },
  { id: "nov-regrouper", text: "Regroupe tes pots contre un mur abrité du vent : serrés, ils se protègent entre eux. Mets les plus fragiles au milieu.", months: [11, 12], condition: "wind" },
  { id: "nov-crosnes", text: "Récolte tes crosnes au fur et à mesure : ils se gardent mieux dans la terre du pot que dans ton frigo, où ils ramollissent en trois jours.", months: [11, 12], plants: ["crosne"] },
  { id: "dec-carnet", text: "Note ce qui a marché cette année et ce qui t’a déçu : c’est la meilleure base pour choisir tes plantes du printemps.", months: [12] },
  { id: "dec-rebord", text: "Même en décembre, ton balcon se cueille : quelques brins de thym, des rosettes de mâche, ou des micro-pousses sur le rebord de ta fenêtre.", months: [12], about: ["thyme", "lambs-lettuce", "microgreens"] },
  { id: "dec-repos", text: "Les jours les plus courts sont là : tes plantes poussent à peine et boivent peu. Arrose seulement si la terre est sèche, jamais quand il gèle.", months: [12] },
  { id: "dec-graines-sec", text: "Range tes graines bien sèches dans une boîte fermée, au frais et à l’abri de la lumière : l’humidité les abîme plus vite que le froid.", months: [12] },
  { id: "dec-oiseaux-eau", text: "Pose une coupelle d’eau pour les oiseaux et change-la quand elle gèle, sans rien y ajouter : en hiver, boire est aussi dur que manger.", months: [12, 1, 2] },
  { id: "dec-citronnier", text: "Ton citronnier rentré boit peu : arrose-le quand la terre est sèche en surface, et garde-le loin du radiateur, qui fait tomber ses feuilles.", months: [12, 1], plants: ["lemon-tree"] },
  { id: "dec-liste-graines", text: "Fais ta liste de graines pour le printemps : piment, poivron et aubergine se sèment au chaud dès février, mieux vaut les avoir sous la main.", months: [12], about: ["chili", "sweet-pepper", "eggplant"] },
  { id: "dec-mache-degel", text: "Cueille ta mâche en coupant la rosette à sa base. S’il gèle, attends le dégel : des feuilles gelées s’abîment dès qu’on les touche.", months: [12, 1, 2], plants: ["lambs-lettuce"], condition: "frost" },
];
